PHRASES = [
    {
        "id": 1,
        "sentence_es": "Quedamos el viernes por la noche — eso suena bien.",
        "sentence_en": "We're meeting on Friday evening — that sounds good.",
        "phrase_es": "suena bien",
        "phrase_en": "sounds good",
    },
    {
        "id": 2,
        "sentence_es": "Nadie sabe si el proyecto saldrá adelante. Que cunda la duda.",
        "sentence_en": "Nobody knows if the project will go ahead. It makes you wonder.",
        "phrase_es": "que cunda la duda",
        "phrase_en": "it makes you wonder / let the doubt spread",
    },
    {
        "id": 3,
        "sentence_es": "No cabe duda de que este restaurante es el mejor de la ciudad.",
        "sentence_en": "There is no doubt that this restaurant is the best in the city.",
        "phrase_es": "no cabe duda",
        "phrase_en": "no doubt about it",
    },
    {
        "id": 4,
        "sentence_es": "¿Que si sé hacer una tortilla española? ¡Pan comido!",
        "sentence_en": "Do I know how to make a Spanish omelette? Piece of cake!",
        "phrase_es": "pan comido",
        "phrase_en": "piece of cake",
    },
    {
        "id": 5,
        "sentence_es": "¿Que si te invito a cenar esta semana? ¡Ya veremos!",
        "sentence_en": "Will I invite you for dinner this week? We'll see!",
        "phrase_es": "¡ya veremos!",
        "phrase_en": "we'll see!",
    },
    {
        "id": 6,
        "sentence_es": "El tráfico a esta hora es un horror — tardé dos horas en llegar.",
        "sentence_en": "The traffic at this hour is awful — it took me two hours to get here.",
        "phrase_es": "es un horror",
        "phrase_en": "it's awful",
    },
    {
        "id": 7,
        "sentence_es": "Me preguntó si me gustaba el nuevo jefe y yo, ¿qué te digo? No me convence.",
        "sentence_en": "He asked me if I liked the new boss and I — what can I say? I'm not convinced.",
        "phrase_es": "¿qué te digo?",
        "phrase_en": "what can I say?",
    },
    {
        "id": 8,
        "sentence_es": "Estábamos cenando tranquilamente cuando, de pronto, se fue la luz.",
        "sentence_en": "We were having dinner calmly when, all of a sudden, the lights went out.",
        "phrase_es": "de pronto",
        "phrase_en": "all of a sudden",
    },
    {
        "id": 9,
        "sentence_es": "No le preguntes nada hoy — tiene mala leche desde que llegó.",
        "sentence_en": "Don't ask him anything today — he has been in a bad mood since he arrived.",
        "phrase_es": "tiene mala leche",
        "phrase_en": "he's in a bad mood / he's in a foul temper",
    },
    {
        "id": 10,
        "sentence_es": "¿Has visto el nuevo apartamento de Marta? ¡Estoy flipando con lo grande que es!",
        "sentence_en": "Have you seen Marta's new flat? I'm amazed at how big it is!",
        "phrase_es": "estoy flipando",
        "phrase_en": "I'm amazed / I can't believe it",
    },
    {
        "id": 11,
        "sentence_es": "¿Que si te presto el coche para el fin de semana? ¡Ni de coña!",
        "sentence_en": "Will I lend you the car for the weekend? Not a chance!",
        "phrase_es": "¡ni de coña!",
        "phrase_en": "not a chance!",
    },
    {
        "id": 12,
        "sentence_es": "¿Me dices que ganaste doscientos euros en la ruleta? ¡Anda ya, no me lo creo!",
        "sentence_en": "You're telling me you won two hundred euros on roulette? Yeah right, I don't believe you!",
        "phrase_es": "¡anda ya!",
        "phrase_en": "yeah right! / you're kidding!",
    },
    {
        "id": 13,
        "sentence_es": "Después de trabajar doce horas seguidas, estoy hecho polvo.",
        "sentence_en": "After working twelve hours straight, I'm absolutely knackered.",
        "phrase_es": "estoy hecho polvo",
        "phrase_en": "I'm knackered / I'm exhausted",
    },
    {
        "id": 14,
        "sentence_es": "¿Has probado el nuevo helado de la heladería? ¡Qué pasada, está buenísimo!",
        "sentence_en": "Have you tried the new ice cream from the parlour? That's amazing, it's delicious!",
        "phrase_es": "¡qué pasada!",
        "phrase_en": "that's amazing! / how cool!",
    },
    {
        "id": 15,
        "sentence_es": "Me encanta el chocolate, pero todo en exceso es malo.",
        "sentence_en": "I love chocolate, but everything in excess is bad.",
        "phrase_es": "todo en exceso es malo",
        "phrase_en": "everything in excess is bad",
    },
    {
        "id": 16,
        "sentence_es": "Llegué diez minutos tarde a la reunión y el jefe me echó la bronca delante de todos.",
        "sentence_en": "I arrived ten minutes late to the meeting and the boss told me off in front of everyone.",
        "phrase_es": "me echó la bronca",
        "phrase_en": "he told me off / he gave me a telling-off",
    },
    {
        "id": 17,
        "sentence_es": "No hace falta que traigas nada — nosotros lo tenemos todo preparado.",
        "sentence_en": "There's no need for you to bring anything — we have everything ready.",
        "phrase_es": "no hace falta",
        "phrase_en": "it's not necessary / there's no need",
    },
    {
        "id": 18,
        "sentence_es": "Desde lo alto de la montaña se veían, en la lejanía, las luces de la ciudad.",
        "sentence_en": "From the top of the mountain you could see, in the distance, the city lights.",
        "phrase_es": "en la lejanía",
        "phrase_en": "in the distance",
    },
    {
        "id": 19,
        "sentence_es": "¡Haz algo, que el agua está empezando a entrar por la ventana!",
        "sentence_en": "Do something — water is starting to come in through the window!",
        "phrase_es": "¡haz algo!",
        "phrase_en": "do something!",
    },
    {
        "id": 20,
        "sentence_es": "No te agobies — lo aprenderemos paso a paso, sin prisa.",
        "sentence_en": "Don't stress — we'll learn it step by step, without rushing.",
        "phrase_es": "paso a paso",
        "phrase_en": "step by step",
    },
    {
        "id": 21,
        "sentence_es": "Estoy a punto de terminar el informe — dame cinco minutos más.",
        "sentence_en": "I'm about to finish the report — give me five more minutes.",
        "phrase_es": "estoy a punto de",
        "phrase_en": "I'm about to...",
    },
    {
        "id": 22,
        "sentence_es": "No veo la hora de que lleguen las vacaciones de verano.",
        "sentence_en": "I can't wait for the summer holidays to arrive.",
        "phrase_es": "no veo la hora de",
        "phrase_en": "I can't wait to...",
    },
    {
        "id": 23,
        "sentence_es": "Le expliqué tres veces la situación, pero ella vive en la luna de Valencia.",
        "sentence_en": "I explained the situation to her three times, but she has her head in the clouds.",
        "phrase_es": "vive en la luna de Valencia",
        "phrase_en": "she has her head in the clouds",
    },
    {
        "id": 24,
        "sentence_es": "Mi abuelo no tiene pelos en la lengua — siempre dice exactamente lo que piensa.",
        "sentence_en": "My grandfather doesn't mince words — he always says exactly what he thinks.",
        "phrase_es": "no tener pelos en la lengua",
        "phrase_en": "not to mince words / to speak very directly",
    },
    {
        "id": 25,
        "sentence_es": "Me muero de ganas de probar la paella de tu madre.",
        "sentence_en": "I'm dying to try your mother's paella.",
        "phrase_es": "me muero de ganas de",
        "phrase_en": "I'm dying to... / I can't wait to...",
    },
    {
        "id": 26,
        "sentence_es": "El trabajo es duro a veces, pero no me puedo quejar — tengo buen equipo.",
        "sentence_en": "Work is hard sometimes, but I can't complain — I have a good team.",
        "phrase_es": "no me puedo quejar",
        "phrase_en": "I can't complain",
    },
    {
        "id": 27,
        "sentence_es": "¿Puedes encargarte de reservar el hotel? — ¡Hecho!",
        "sentence_en": "Can you take care of booking the hotel? — Consider it done!",
        "phrase_es": "¡hecho!",
        "phrase_en": "consider it done!",
    },
    {
        "id": 28,
        "sentence_es": "¿Te molesta si ponemos la música un poco más alta? — En absoluto, adelante.",
        "sentence_en": "Does it bother you if we turn the music up a bit? — Absolutely not, go ahead.",
        "phrase_es": "en absoluto",
        "phrase_en": "absolutely not",
    },
    {
        "id": 29,
        "sentence_es": "Conseguir ese trabajo en Madrid fue, para mí, un sueño hecho realidad.",
        "sentence_en": "Getting that job in Madrid was, for me, a dream come true.",
        "phrase_es": "un sueño hecho realidad",
        "phrase_en": "a dream come true",
    },
    {
        "id": 30,
        "sentence_es": "No corras tanto con la traducción — tómate tu tiempo, no hay prisa.",
        "sentence_en": "Don't rush the translation — take your time, there's no hurry.",
        "phrase_es": "tómate tu tiempo, no hay prisa",
        "phrase_en": "take your time, there's no rush",
    },
    {
        "id": 31,
        "sentence_es": "¡No salgas sin el chubasquero — llueve a cántaros!",
        "sentence_en": "Don't go out without your waterproof — it's raining buckets!",
        "phrase_es": "llueve a cántaros",
        "phrase_en": "it's raining buckets",
    },
    {
        "id": 32,
        "sentence_es": "¿Ya habéis decidido adónde vais de vacaciones? — Todavía no, estamos mirando opciones.",
        "sentence_en": "Have you decided yet where you're going on holiday? — Not yet, we're looking at options.",
        "phrase_es": "todavía no",
        "phrase_en": "not yet",
    },
    {
        "id": 33,
        "sentence_es": "Han pasado dos años desde que empecé y sigo estudiando español con mucho entusiasmo.",
        "sentence_en": "Two years have passed since I started and I'm still studying Spanish with great enthusiasm.",
        "phrase_es": "sigo estudiando español",
        "phrase_en": "I'm still studying Spanish",
    },
    {
        "id": 34,
        "sentence_es": "Antes salía a correr todas las mañanas, pero ya no — tengo las rodillas mal.",
        "sentence_en": "I used to go running every morning, but not anymore — my knees are bad.",
        "phrase_es": "ya no",
        "phrase_en": "not anymore",
    },
    {
        "id": 35,
        "sentence_es": "Cálmate, hombre — no es para tanto, solo es un pequeño error.",
        "sentence_en": "Calm down — it's not a big deal, it's just a small mistake.",
        "phrase_es": "no es para tanto",
        "phrase_en": "it's not a big deal / don't exaggerate",
    },
    {
        "id": 36,
        "sentence_es": "Es un asunto entre ellos dos — no te metas, que luego te arrepientes.",
        "sentence_en": "It's a matter between the two of them — don't get involved, you'll regret it.",
        "phrase_es": "no te metas",
        "phrase_en": "don't get involved / mind your own business",
    },
    {
        "id": 37,
        "sentence_es": "No fui yo quien rompió la ventana — te lo juro.",
        "sentence_en": "It wasn't me who broke the window — I swear it.",
        "phrase_es": "te lo juro",
        "phrase_en": "I swear it / I swear to you",
    },
    {
        "id": 38,
        "sentence_es": "Disfruta del verano mientras puedas — se va a acabar antes de que te des cuenta.",
        "sentence_en": "Enjoy the summer while you can — it'll be over before you know it.",
        "phrase_es": "se va a acabar",
        "phrase_en": "it's going to end / it'll be over",
    },
    {
        "id": 39,
        "sentence_es": "Para el coche un momento, que voy a mear — no aguanto más.",
        "sentence_en": "Stop the car for a moment — I need to pee, I can't hold on any longer.",
        "phrase_es": "voy a mear",
        "phrase_en": "I'm going to pee",
    },
    {
        "id": 40,
        "sentence_es": "Los soldados pasaron toda la noche en la trinchera bajo la lluvia.",
        "sentence_en": "The soldiers spent the whole night in the trench in the rain.",
        "phrase_es": "la trinchera",
        "phrase_en": "the trench",
    },
    {
        "id": 41,
        "sentence_es": "No me gusta ese barrio — está muy chungo por las noches.",
        "sentence_en": "I don't like that neighbourhood — it's very sketchy at night.",
        "phrase_es": "muy chungo",
        "phrase_en": "very bad / really sketchy",
    },
    {
        "id": 42,
        "sentence_es": "La gata de mi vecina se subió al tejado y no quería bajar.",
        "sentence_en": "My neighbour's cat climbed onto the roof and didn't want to come down.",
        "phrase_es": "la gata",
        "phrase_en": "the (female) cat",
    },
    {
        "id": 43,
        "sentence_es": "¿Vais al concierto el sábado? Yo me apunto — me encanta ese grupo.",
        "sentence_en": "Are you going to the concert on Saturday? Count me in — I love that band.",
        "phrase_es": "yo me apunto",
        "phrase_en": "I'm in / count me in",
    },
    {
        "id": 44,
        "sentence_es": "Después de meses de práctica, por fin tengo cogido el tiempo al bailar salsa.",
        "sentence_en": "After months of practice, I've finally got the hang of the timing when dancing salsa.",
        "phrase_es": "cogido el tiempo",
        "phrase_en": "got the timing right / got the hang of it",
    },
    {
        "id": 45,
        "sentence_es": "Que encontráramos un taxi libre a esas horas fue un auténtico milagro.",
        "sentence_en": "Finding a free taxi at that hour was a genuine miracle.",
        "phrase_es": "un milagro",
        "phrase_en": "a miracle",
    },
    {
        "id": 46,
        "sentence_es": "Llamé a un fontanero barato y solo hizo chapuzas — tuve que pagar el doble para arreglarlo.",
        "sentence_en": "I called a cheap plumber and he only did shoddy work — I had to pay double to get it fixed.",
        "phrase_es": "chapuzas",
        "phrase_en": "shoddy work / botched jobs",
    },
    {
        "id": 47,
        "sentence_es": "En esa reunión los directivos tomaron todas las decisiones — nosotros no pintamos un carajo.",
        "sentence_en": "In that meeting the managers made all the decisions — we had no say whatsoever.",
        "phrase_es": "no pintamos un carajo",
        "phrase_en": "we have no say / we don't matter at all",
    },
    {
        "id": 48,
        "sentence_es": "Tienes que entregar el proyecto antes del viernes sin falta.",
        "sentence_en": "You have to hand in the project by Friday without fail.",
        "phrase_es": "entregar",
        "phrase_en": "to deliver / to hand over",
    },
    {
        "id": 49,
        "sentence_es": "Se acabó la paciencia — o llegáis a tiempo o no venís.",
        "sentence_en": "That's it, patience is over — either you arrive on time or you don't come.",
        "phrase_es": "se acabó",
        "phrase_en": "it's over / that's it",
    },
    {
        "id": 50,
        "sentence_es": "Me da palo llamarle después de tanto tiempo sin hablar.",
        "sentence_en": "I can't be bothered to call him after so long without speaking.",
        "phrase_es": "me da palo",
        "phrase_en": "I can't be bothered / I'm reluctant",
    },
    {
        "id": 51,
        "sentence_es": "¿Que te dijo eso delante de todos? ¡Qué fuerte, no me lo puedo creer!",
        "sentence_en": "He said that to you in front of everyone? Wow, I can't believe it!",
        "phrase_es": "¡qué fuerte!",
        "phrase_en": "wow! / that's intense! / unbelievable!",
    },
    {
        "id": 52,
        "sentence_es": "No te preocupes por la receta — está tirado, te lo explico en dos minutos.",
        "sentence_en": "Don't worry about the recipe — it's dead easy, I'll explain it to you in two minutes.",
        "phrase_es": "está tirado",
        "phrase_en": "it's dead easy / a doddle",
    },
    {
        "id": 53,
        "sentence_es": "Ya sé que llegué tarde — ¡no me ralles más con eso!",
        "sentence_en": "I know I was late — stop doing my head in about it!",
        "phrase_es": "no me ralles",
        "phrase_en": "don't do my head in / stop stressing me out",
    },
    {
        "id": 54,
        "sentence_es": "Llámame luego, que ahora voy justo de tiempo para coger el tren.",
        "sentence_en": "Call me later, I'm running short on time to catch the train.",
        "phrase_es": "voy justo de tiempo",
        "phrase_en": "I'm running short on time",
    },
    {
        "id": 55,
        "sentence_es": "Me han pedido que organice la boda yo solo. ¡Menudo marrón!",
        "sentence_en": "They've asked me to organise the wedding by myself. What a nightmare!",
        "phrase_es": "menudo marrón",
        "phrase_en": "what a mess / what a nightmare",
    },
    {
        "id": 56,
        "sentence_es": "¿Ahora me preguntas eso? Me pillas fatal — estoy en medio de una reunión.",
        "sentence_en": "You're asking me that now? You've caught me at a really bad time — I'm in the middle of a meeting.",
        "phrase_es": "me pillas fatal",
        "phrase_en": "you've caught me at a really bad time",
    },
    {
        "id": 57,
        "sentence_es": "No me apetece salir esta noche — prefiero quedarme en el sofá viendo una serie.",
        "sentence_en": "I don't feel like going out tonight — I'd rather stay on the sofa watching a series.",
        "phrase_es": "no me apetece",
        "phrase_en": "I don't feel like it / I'm not in the mood",
    },
    {
        "id": 58,
        "sentence_es": "Llevar el coche a la ITV siempre es un coñazo — te tienes que organizar el día entero.",
        "sentence_en": "Taking the car for its MOT is always such a pain — you have to plan your whole day around it.",
        "phrase_es": "qué coñazo",
        "phrase_en": "what a pain / what a hassle",
    },
    {
        "id": 59,
        "sentence_es": "Estoy hasta las narices de las reuniones que no sirven para nada.",
        "sentence_en": "I'm fed up with meetings that serve no purpose.",
        "phrase_es": "estoy hasta las narices",
        "phrase_en": "I'm fed up / I've had enough",
    },
    {
        "id": 60,
        "sentence_es": "Madrugar el sábado para una reunión de media hora no tiene sentido.",
        "sentence_en": "Getting up early on Saturday for a half-hour meeting makes no sense.",
        "phrase_es": "no tiene sentido",
        "phrase_en": "it makes no sense / that's pointless",
    },
    {
        "id": 61,
        "sentence_es": "Iba a pedir un aumento, pero al final se echó atrás en el último momento.",
        "sentence_en": "He was going to ask for a raise, but in the end he chickened out at the last minute.",
        "phrase_es": "se echó atrás",
        "phrase_en": "he/she chickened out / backed off",
    },
    {
        "id": 62,
        "sentence_es": "No sé si podré ir a la cena del viernes — vamos viendo cómo está la semana.",
        "sentence_en": "I don't know if I'll be able to make the Friday dinner — let's see how the week goes.",
        "phrase_es": "vamos viendo",
        "phrase_en": "let's see how it goes / we'll see",
    },
    {
        "id": 63,
        "sentence_es": "Iba a llegar a tiempo, pero me pilló un atasco enorme en la autopista.",
        "sentence_en": "I was going to arrive on time, but I got caught in a huge traffic jam on the motorway.",
        "phrase_es": "me pilló",
        "phrase_en": "it caught me / I got caught",
    },
    {
        "id": 64,
        "sentence_es": "Llegué tarde a la cita pero él dijo que no importa, que había esperado con gusto.",
        "sentence_en": "I arrived late to the appointment but he said it doesn't matter, he was happy to wait.",
        "phrase_es": "no importa",
        "phrase_en": "it doesn't matter",
    },
    {
        "id": 65,
        "sentence_es": "Los domingos por la tarde me aburro como una ostra si no tengo planes.",
        "sentence_en": "On Sunday afternoons I'm bored out of my mind if I have no plans.",
        "phrase_es": "me aburro como una ostra",
        "phrase_en": "I'm bored out of my mind (lit: bored like an oyster)",
    },
    {
        "id": 66,
        "sentence_es": "El examen es mañana — cruzamos los dedos para que todo salga bien.",
        "sentence_en": "The exam is tomorrow — we'll keep our fingers crossed that everything goes well.",
        "phrase_es": "cruzamos los dedos",
        "phrase_en": "we'll keep our fingers crossed",
    },
    {
        "id": 67,
        "sentence_es": "Con el paso del tiempo, aprendes a no preocuparte tanto por las pequeñas cosas.",
        "sentence_en": "With the passage of time, you learn not to worry so much about small things.",
        "phrase_es": "con el paso del tiempo",
        "phrase_en": "with the passage of time",
    },
    {
        "id": 68,
        "sentence_es": "¿Vamos al cine o al teatro esta noche? — Que más da, los dos me apetecen.",
        "sentence_en": "Shall we go to the cinema or the theatre tonight? — Who cares, I fancy both.",
        "phrase_es": "que más da",
        "phrase_en": "who cares? / it doesn't matter either way",
    },
    {
        "id": 69,
        "sentence_es": "El viaje a Japón es algo que me hace ilusión desde hace años.",
        "sentence_en": "The trip to Japan is something I've been really looking forward to for years.",
        "phrase_es": "me hace ilusión",
        "phrase_en": "it excites me / I'm really looking forward to it",
    },
    {
        "id": 70,
        "sentence_es": "¿Qué pasa, quillo? ¿Todo bien por ahí?",
        "sentence_en": "What's up, mate? Everything alright over there?",
        "phrase_es": "¿qué pasa, quillo/quilla?",
        "phrase_en": "what's up? (very Andalusian, casual)",
    },
    {
        "id": 71,
        "sentence_es": "Hace un calor aquí dentro… no veas.",
        "sentence_en": "It is seriously hot in here, you've no idea.",
        "phrase_es": "no veas",
        "phrase_en": "you've no idea / seriously / it was a lot",
    },
    {
        "id": 72,
        "sentence_es": "¡Qué calor, miarma! Vamos a buscar la sombra.",
        "sentence_en": "It's roasting, love! Let's find some shade.",
        "phrase_es": "¡qué calor, miarma!",
        "phrase_en": "it's roasting, love! (miarma = mi alma, very Sevillian)",
    },
    {
        "id": 73,
        "sentence_es": "Después de trabajar todo el fin de semana, estoy reventao.",
        "sentence_en": "After working all weekend, I'm absolutely exhausted.",
        "phrase_es": "estoy reventao / reventá",
        "phrase_en": "I'm exhausted / worn out",
    },
    {
        "id": 74,
        "sentence_es": "No me esperes en el bar — voy del tirón desde la oficina.",
        "sentence_en": "Don't wait for me at the bar — I'm heading straight there from the office.",
        "phrase_es": "voy del tirón",
        "phrase_en": "I'm going straight there / heading over now without stopping",
    },
    {
        "id": 75,
        "sentence_es": "Hablé con el mecánico esta mañana y eso está apañao.",
        "sentence_en": "I spoke to the mechanic this morning and that's all sorted.",
        "phrase_es": "eso está apañao",
        "phrase_en": "that's sorted",
    },
    {
        "id": 76,
        "sentence_es": "No te rayes — seguro que llega en un momento.",
        "sentence_en": "Don't overthink it — I'm sure he'll be here any minute.",
        "phrase_es": "no te rayes",
        "phrase_en": "don't overthink it / don't stress",
    },
    {
        "id": 77,
        "sentence_es": "Nos comimos una paella entera entre los dos — qué pechá.",
        "sentence_en": "We ate a whole paella between the two of us — what a marathon.",
        "phrase_es": "qué pechá",
        "phrase_en": "what a huge amount / what a marathon (food, work, anything excessive)",
    },
    {
        "id": 78,
        "sentence_es": "Me da coraje que siempre llegue tarde y no diga nada.",
        "sentence_en": "It really gets on my nerves that he always arrives late and says nothing.",
        "phrase_es": "me da coraje",
        "phrase_en": "it annoys me / it really gets on my nerves",
    },
    {
        "id": 79,
        "sentence_es": "¿Has probado el nuevo bar de la plaza? Está del carajo.",
        "sentence_en": "Have you tried the new bar on the square? It's absolutely brilliant.",
        "phrase_es": "está del carajo",
        "phrase_en": "it's brilliant / it's great",
    },
    {
        "id": 80,
        "sentence_es": "¿Ha dormido algo el niño esta noche? — Ni mijita.",
        "sentence_en": "Did the little one sleep at all last night? — Not even a tiny bit.",
        "phrase_es": "ni mijita",
        "phrase_en": "not even a little bit (very southern)",
    },
    {
        "id": 81,
        "sentence_es": "No hace falta que vengas ahora mismo — ahora después te llamo.",
        "sentence_en": "No need to come right now — I'll call you later on.",
        "phrase_es": "ahora después",
        "phrase_en": "later on (not immediately — just at some point later)",
    },
    {
        "id": 82,
        "sentence_es": "¿Que si me gustó la boda? No ni ná — fue espectacular.",
        "sentence_en": "Did I like the wedding? Absolutely — it was spectacular.",
        "phrase_es": "no ni ná",
        "phrase_en": "of course / absolutely / you bet (very Andalusian strong agreement)",
    },
    {
        "id": 83,
        "sentence_es": "Me cobran cien euros por arreglar eso — tiene guasa.",
        "sentence_en": "They're charging me a hundred euros to fix that — that's a bit rich.",
        "phrase_es": "tiene guasa",
        "phrase_en": "that's ridiculous / that's rich / it's got a nerve",
    },
    {
        "id": 84,
        "sentence_es": "Vente p'acá, que te cuento lo que pasó anoche.",
        "sentence_en": "Come over here, I'll tell you what happened last night.",
        "phrase_es": "vente p'acá",
        "phrase_en": "come over here",
    },
    {
        "id": 85,
        "sentence_es": "No tenemos planes — ¿vamos a echar un rato en el parque?",
        "sentence_en": "We've got no plans — shall we go hang out in the park for a bit?",
        "phrase_es": "vamos a echar un rato",
        "phrase_en": "let's hang out for a bit",
    },
    {
        "id": 86,
        "sentence_es": "Me he tumbado en el sofá con el café — estoy en la gloria.",
        "sentence_en": "I've settled on the sofa with my coffee — I'm in heaven.",
        "phrase_es": "estoy en la gloria",
        "phrase_en": "I'm in heaven / I'm perfectly comfortable",
    },
    {
        "id": 87,
        "sentence_es": "Hoy en la playa hacía un levante que no veas — casi no podíamos andar.",
        "sentence_en": "At the beach today the wind was unbelievable — we could barely walk.",
        "phrase_es": "hace un levante que no veas",
        "phrase_en": "the easterly wind is unbelievable (very common near Cádiz)",
    },
    {
        "id": 88,
        "sentence_es": "Montó la decoración entera ella sola en una hora — qué arte tienes, tía.",
        "sentence_en": "She put up the whole decoration by herself in an hour — you're brilliant, honestly.",
        "phrase_es": "qué arte tienes",
        "phrase_en": "you're brilliant / you've got style / you're hilarious (Andalusian compliment)",
    },
    {
        "id": 89,
        "sentence_es": "Illo, espérate un momento, que no encuentro las llaves.",
        "sentence_en": "Mate, wait a second, I can't find my keys.",
        "phrase_es": "illo, espérate un momento",
        "phrase_en": "mate, wait a second (illo = chiquillo, very Andalusian)",
    },
]
