TENSES = [
    "Presente de indicativo",
    "Pretérito indefinido",
    "Pretérito imperfecto",
    "Pretérito perfecto compuesto",
    "Futuro simple",
    "Condicional simple",
    "Presente de subjuntivo",
    "Imperativo",
]

SENTENCES = [
    # ── Presente de indicativo ──────────────────────────────────────────────
    {
        "id": 1,
        "spanish": "Todos los días como una manzana en el desayuno.",
        "english": "Every day I eat an apple for breakfast.",
        "verb_form": "como",
        "verb_infinitive": "comer",
        "tense": "Presente de indicativo",
        "explanation": "\"Como\" is the present indicative of comer (1st person singular), describing a habitual action.",
    },
    {
        "id": 2,
        "spanish": "Mi hermana trabaja en un hospital del centro.",
        "english": "My sister works at a hospital in the city centre.",
        "verb_form": "trabaja",
        "verb_infinitive": "trabajar",
        "tense": "Presente de indicativo",
        "explanation": "\"Trabaja\" is the present indicative of trabajar (3rd person singular).",
    },
    {
        "id": 3,
        "spanish": "Nosotros vivimos cerca de la playa.",
        "english": "We live near the beach.",
        "verb_form": "vivimos",
        "verb_infinitive": "vivir",
        "tense": "Presente de indicativo",
        "explanation": "\"Vivimos\" is the present indicative of vivir (1st person plural).",
    },
    {
        "id": 4,
        "spanish": "¿Hablas español con tu familia en casa?",
        "english": "Do you speak Spanish with your family at home?",
        "verb_form": "hablas",
        "verb_infinitive": "hablar",
        "tense": "Presente de indicativo",
        "explanation": "\"Hablas\" is the present indicative of hablar (2nd person singular).",
    },
    {
        "id": 5,
        "spanish": "Los niños juegan en el parque por las tardes.",
        "english": "The children play in the park in the afternoons.",
        "verb_form": "juegan",
        "verb_infinitive": "jugar",
        "tense": "Presente de indicativo",
        "explanation": "\"Juegan\" is the present indicative of the stem-changing verb jugar (3rd person plural).",
    },
    {
        "id": 6,
        "spanish": "El tren sale a las nueve de la mañana.",
        "english": "The train leaves at nine in the morning.",
        "verb_form": "sale",
        "verb_infinitive": "salir",
        "tense": "Presente de indicativo",
        "explanation": "\"Sale\" is the present indicative of salir (3rd person singular).",
    },
    {
        "id": 7,
        "spanish": "Vosotros estudiáis mucho para los exámenes.",
        "english": "You all study a lot for the exams.",
        "verb_form": "estudiáis",
        "verb_infinitive": "estudiar",
        "tense": "Presente de indicativo",
        "explanation": "\"Estudiáis\" is the present indicative of estudiar (2nd person plural, vosotros).",
    },
    {
        "id": 8,
        "spanish": "Siempre llueve mucho en otoño en el norte.",
        "english": "It always rains a lot in autumn in the north.",
        "verb_form": "llueve",
        "verb_infinitive": "llover",
        "tense": "Presente de indicativo",
        "explanation": "\"Llueve\" is the present indicative of the impersonal verb llover.",
    },

    # ── Pretérito indefinido ────────────────────────────────────────────────
    {
        "id": 9,
        "spanish": "Ayer comí una paella deliciosa en el restaurante.",
        "english": "Yesterday I ate a delicious paella at the restaurant.",
        "verb_form": "comí",
        "verb_infinitive": "comer",
        "tense": "Pretérito indefinido",
        "explanation": "\"Comí\" is the preterite of comer (1st person singular). The word ayer confirms a completed past action.",
    },
    {
        "id": 10,
        "spanish": "María llegó a casa muy tarde anoche.",
        "english": "María arrived home very late last night.",
        "verb_form": "llegó",
        "verb_infinitive": "llegar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Llegó\" is the preterite of llegar (3rd person singular), a completed action in the past.",
    },
    {
        "id": 11,
        "spanish": "Los estudiantes aprobaron todos los exámenes finales.",
        "english": "The students passed all the final exams.",
        "verb_form": "aprobaron",
        "verb_infinitive": "aprobar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Aprobaron\" is the preterite of aprobar (3rd person plural).",
    },
    {
        "id": 12,
        "spanish": "El partido terminó con un resultado de tres a uno.",
        "english": "The match ended with a score of three to one.",
        "verb_form": "terminó",
        "verb_infinitive": "terminar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Terminó\" is the preterite of terminar (3rd person singular).",
    },
    {
        "id": 13,
        "spanish": "¿Cuándo empezaste a estudiar español?",
        "english": "When did you start studying Spanish?",
        "verb_form": "empezaste",
        "verb_infinitive": "empezar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Empezaste\" is the preterite of empezar (2nd person singular).",
    },
    {
        "id": 14,
        "spanish": "Bebieron demasiado vino en la cena de Navidad.",
        "english": "They drank too much wine at the Christmas dinner.",
        "verb_form": "bebieron",
        "verb_infinitive": "beber",
        "tense": "Pretérito indefinido",
        "explanation": "\"Bebieron\" is the preterite of beber (3rd person plural).",
    },
    {
        "id": 15,
        "spanish": "Anteayer hablé con mi madre por teléfono durante una hora.",
        "english": "The day before yesterday I spoke with my mother on the phone for an hour.",
        "verb_form": "hablé",
        "verb_infinitive": "hablar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Hablé\" is the preterite of hablar (1st person singular).",
    },
    {
        "id": 16,
        "spanish": "El año pasado viajamos a Madrid durante las vacaciones.",
        "english": "Last year we travelled to Madrid during the holidays.",
        "verb_form": "viajamos",
        "verb_infinitive": "viajar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Viajamos\" here is the preterite of viajar — the phrase \"el año pasado\" signals a completed past event.",
    },

    # ── Pretérito imperfecto ────────────────────────────────────────────────
    {
        "id": 17,
        "spanish": "Cuando era niño, vivía en un pueblo pequeño del norte.",
        "english": "When I was a child, I lived in a small town in the north.",
        "verb_form": "vivía",
        "verb_infinitive": "vivir",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Vivía\" is the imperfect of vivir, describing an ongoing past situation.",
    },
    {
        "id": 18,
        "spanish": "De pequeña, mi abuela cocinaba todos los domingos para la familia.",
        "english": "When she was little, my grandmother cooked for the family every Sunday.",
        "verb_form": "cocinaba",
        "verb_infinitive": "cocinar",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Cocinaba\" is the imperfect of cocinar, describing a repeated past habit.",
    },
    {
        "id": 19,
        "spanish": "Antes, los niños jugaban más en la calle y menos con el móvil.",
        "english": "Before, children used to play more in the street and less with their phones.",
        "verb_form": "jugaban",
        "verb_infinitive": "jugar",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Jugaban\" is the imperfect of jugar, describing a habitual past activity.",
    },
    {
        "id": 20,
        "spanish": "Cuando llegué a casa, mis hijos dormían tranquilamente.",
        "english": "When I arrived home, my children were sleeping peacefully.",
        "verb_form": "dormían",
        "verb_infinitive": "dormir",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Dormían\" is the imperfect of dormir — an ongoing action interrupted by another (llegué).",
    },
    {
        "id": 21,
        "spanish": "Todos los veranos íbamos a la playa con los abuelos.",
        "english": "Every summer we used to go to the beach with our grandparents.",
        "verb_form": "íbamos",
        "verb_infinitive": "ir",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Íbamos\" is the imperfect of the irregular verb ir, expressing a past routine.",
    },
    {
        "id": 22,
        "spanish": "Cuando era joven, soñaba con ser astronauta.",
        "english": "When I was young, I used to dream of being an astronaut.",
        "verb_form": "soñaba",
        "verb_infinitive": "soñar",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Soñaba\" is the imperfect of soñar, describing a recurring past wish.",
    },
    {
        "id": 23,
        "spanish": "En aquella época, la gente no tenía teléfonos móviles.",
        "english": "In those days, people didn't have mobile phones.",
        "verb_form": "tenía",
        "verb_infinitive": "tener",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Tenía\" is the imperfect of tener, describing a past state.",
    },
    {
        "id": 24,
        "spanish": "Mientras estudiaba, escuchaba música clásica.",
        "english": "While I was studying, I was listening to classical music.",
        "verb_form": "estudiaba",
        "verb_infinitive": "estudiar",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Estudiaba\" is the imperfect of estudiar, describing two simultaneous ongoing past actions.",
    },

    # ── Pretérito perfecto compuesto ────────────────────────────────────────
    {
        "id": 25,
        "spanish": "Esta mañana he desayunado con mi familia antes del trabajo.",
        "english": "This morning I had breakfast with my family before work.",
        "verb_form": "he desayunado",
        "verb_infinitive": "desayunar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"He desayunado\" is the present perfect of desayunar. \"Esta mañana\" signals a recently completed action.",
    },
    {
        "id": 26,
        "spanish": "¿Alguna vez has visitado la Sagrada Familia en Barcelona?",
        "english": "Have you ever visited the Sagrada Família in Barcelona?",
        "verb_form": "has visitado",
        "verb_infinitive": "visitar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Has visitado\" is the present perfect of visitar, used for life experiences with \"alguna vez\".",
    },
    {
        "id": 27,
        "spanish": "Esta semana hemos trabajado muchísimo para terminar el proyecto.",
        "english": "This week we have worked a great deal to finish the project.",
        "verb_form": "hemos trabajado",
        "verb_infinitive": "trabajar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Hemos trabajado\" is the present perfect of trabajar. \"Esta semana\" links the action to the present period.",
    },
    {
        "id": 28,
        "spanish": "Mis padres han comprado una casa nueva en las afueras.",
        "english": "My parents have bought a new house on the outskirts.",
        "verb_form": "han comprado",
        "verb_infinitive": "comprar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Han comprado\" is the present perfect of comprar (3rd person plural).",
    },
    {
        "id": 29,
        "spanish": "Hoy el ministro ha anunciado cambios importantes en la ley.",
        "english": "Today the minister has announced important changes to the law.",
        "verb_form": "ha anunciado",
        "verb_infinitive": "anunciar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Ha anunciado\" is the present perfect of anunciar. \"Hoy\" places it in the current time frame.",
    },
    {
        "id": 30,
        "spanish": "Nunca he probado el gazpacho andaluz.",
        "english": "I have never tried Andalusian gazpacho.",
        "verb_form": "he probado",
        "verb_infinitive": "probar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"He probado\" with \"nunca\" is a classic present perfect structure for life experiences.",
    },
    {
        "id": 31,
        "spanish": "¿Ya habéis terminado los deberes para mañana?",
        "english": "Have you all already finished the homework for tomorrow?",
        "verb_form": "habéis terminado",
        "verb_infinitive": "terminar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Habéis terminado\" is the present perfect of terminar (2nd person plural, vosotros).",
    },
    {
        "id": 32,
        "spanish": "Este año España ha ganado varios premios internacionales.",
        "english": "This year Spain has won several international awards.",
        "verb_form": "ha ganado",
        "verb_infinitive": "ganar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Ha ganado\" is the present perfect of ganar. \"Este año\" connects to the ongoing present year.",
    },

    # ── Futuro simple ───────────────────────────────────────────────────────
    {
        "id": 33,
        "spanish": "El próximo verano viajaré por toda Andalucía.",
        "english": "Next summer I will travel all around Andalusia.",
        "verb_form": "viajaré",
        "verb_infinitive": "viajar",
        "tense": "Futuro simple",
        "explanation": "\"Viajaré\" is the simple future of viajar (1st person singular).",
    },
    {
        "id": 34,
        "spanish": "Mañana hará mucho calor en el sur de España.",
        "english": "Tomorrow it will be very hot in southern Spain.",
        "verb_form": "hará",
        "verb_infinitive": "hacer",
        "tense": "Futuro simple",
        "explanation": "\"Hará\" is the simple future of the irregular verb hacer (3rd person singular).",
    },
    {
        "id": 35,
        "spanish": "Cuando termines los estudios, encontrarás un buen trabajo.",
        "english": "When you finish your studies, you will find a good job.",
        "verb_form": "encontrarás",
        "verb_infinitive": "encontrar",
        "tense": "Futuro simple",
        "explanation": "\"Encontrarás\" is the simple future of encontrar (2nd person singular).",
    },
    {
        "id": 36,
        "spanish": "El concierto empezará a las nueve y terminará a medianoche.",
        "english": "The concert will start at nine and end at midnight.",
        "verb_form": "empezará",
        "verb_infinitive": "empezar",
        "tense": "Futuro simple",
        "explanation": "\"Empezará\" is the simple future of empezar (3rd person singular).",
    },
    {
        "id": 37,
        "spanish": "El año que viene construirán un nuevo hospital en esta ciudad.",
        "english": "Next year they will build a new hospital in this city.",
        "verb_form": "construirán",
        "verb_infinitive": "construir",
        "tense": "Futuro simple",
        "explanation": "\"Construirán\" is the simple future of construir (3rd person plural).",
    },
    {
        "id": 38,
        "spanish": "Prometo que vendré a tu boda sin falta.",
        "english": "I promise I will come to your wedding without fail.",
        "verb_form": "vendré",
        "verb_infinitive": "venir",
        "tense": "Futuro simple",
        "explanation": "\"Vendré\" is the simple future of the irregular verb venir (1st person singular).",
    },
    {
        "id": 39,
        "spanish": "¿Cuánto tiempo tardaréis en llegar a Madrid desde aquí?",
        "english": "How long will it take you all to get to Madrid from here?",
        "verb_form": "tardaréis",
        "verb_infinitive": "tardar",
        "tense": "Futuro simple",
        "explanation": "\"Tardaréis\" is the simple future of tardar (2nd person plural, vosotros).",
    },
    {
        "id": 40,
        "spanish": "No sé dónde estará mi pasaporte; lo buscaré después.",
        "english": "I don't know where my passport will be; I'll look for it later.",
        "verb_form": "estará",
        "verb_infinitive": "estar",
        "tense": "Futuro simple",
        "explanation": "\"Estará\" is the simple future of estar, used here to express probability or conjecture.",
    },

    # ── Condicional simple ──────────────────────────────────────────────────
    {
        "id": 41,
        "spanish": "Si tuviera más dinero, compraría una casa en la playa.",
        "english": "If I had more money, I would buy a house on the beach.",
        "verb_form": "compraría",
        "verb_infinitive": "comprar",
        "tense": "Condicional simple",
        "explanation": "\"Compraría\" is the conditional of comprar, used in a hypothetical if-clause.",
    },
    {
        "id": 42,
        "spanish": "¿Podrías ayudarme con este ejercicio, por favor?",
        "english": "Could you help me with this exercise, please?",
        "verb_form": "podrías",
        "verb_infinitive": "poder",
        "tense": "Condicional simple",
        "explanation": "\"Podrías\" is the conditional of the irregular poder, used for polite requests.",
    },
    {
        "id": 43,
        "spanish": "Me dijo que llamaría cuando llegara a casa.",
        "english": "He told me he would call when he got home.",
        "verb_form": "llamaría",
        "verb_infinitive": "llamar",
        "tense": "Condicional simple",
        "explanation": "\"Llamaría\" is the conditional of llamar, used as a future-in-the-past after a reporting verb.",
    },
    {
        "id": 44,
        "spanish": "En tu lugar, hablaría directamente con el director.",
        "english": "In your place, I would speak directly to the director.",
        "verb_form": "hablaría",
        "verb_infinitive": "hablar",
        "tense": "Condicional simple",
        "explanation": "\"Hablaría\" is the conditional of hablar, giving advice about a hypothetical situation.",
    },
    {
        "id": 45,
        "spanish": "¿Sabrías cómo llegar a la catedral desde aquí?",
        "english": "Would you happen to know how to get to the cathedral from here?",
        "verb_form": "sabrías",
        "verb_infinitive": "saber",
        "tense": "Condicional simple",
        "explanation": "\"Sabrías\" is the conditional of the irregular saber, softening a question politely.",
    },
    {
        "id": 46,
        "spanish": "Con más tiempo libre, estudiaríamos mucho mejor.",
        "english": "With more free time, we would study much better.",
        "verb_form": "estudiaríamos",
        "verb_infinitive": "estudiar",
        "tense": "Condicional simple",
        "explanation": "\"Estudiaríamos\" is the conditional of estudiar (1st person plural).",
    },
    {
        "id": 47,
        "spanish": "¿Querrías venir a la fiesta del sábado con nosotros?",
        "english": "Would you like to come to the Saturday party with us?",
        "verb_form": "querrías",
        "verb_infinitive": "querer",
        "tense": "Condicional simple",
        "explanation": "\"Querrías\" is the conditional of the irregular querer, used for a polite invitation.",
    },
    {
        "id": 48,
        "spanish": "Pensaban que el proyecto costaría mucho menos.",
        "english": "They thought the project would cost much less.",
        "verb_form": "costaría",
        "verb_infinitive": "costar",
        "tense": "Condicional simple",
        "explanation": "\"Costaría\" is the conditional of costar, expressing a past expectation about the future.",
    },

    # ── Presente de subjuntivo ──────────────────────────────────────────────
    {
        "id": 49,
        "spanish": "Espero que llegues a tiempo para la reunión.",
        "english": "I hope you arrive on time for the meeting.",
        "verb_form": "llegues",
        "verb_infinitive": "llegar",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Llegues\" is the present subjunctive of llegar, triggered by \"espero que\".",
    },
    {
        "id": 50,
        "spanish": "El médico recomienda que bebas mucha agua cada día.",
        "english": "The doctor recommends that you drink plenty of water each day.",
        "verb_form": "bebas",
        "verb_infinitive": "beber",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Bebas\" is the present subjunctive of beber, triggered by \"recomienda que\".",
    },
    {
        "id": 51,
        "spanish": "Es importante que hagamos ejercicio con regularidad.",
        "english": "It is important that we exercise regularly.",
        "verb_form": "hagamos",
        "verb_infinitive": "hacer",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Hagamos\" is the present subjunctive of the irregular hacer, following the impersonal \"es importante que\".",
    },
    {
        "id": 52,
        "spanish": "No creo que tenga razón en este asunto.",
        "english": "I don't think he is right about this matter.",
        "verb_form": "tenga",
        "verb_infinitive": "tener",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Tenga\" is the present subjunctive of tener, triggered by the negative \"no creo que\".",
    },
    {
        "id": 53,
        "spanish": "Busco a alguien que sepa hablar chino con fluidez.",
        "english": "I am looking for someone who can speak Chinese fluently.",
        "verb_form": "sepa",
        "verb_infinitive": "saber",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Sepa\" is the present subjunctive of saber, used in a relative clause with an unknown/indefinite antecedent.",
    },
    {
        "id": 54,
        "spanish": "Ojalá que mañana haga buen tiempo para el picnic.",
        "english": "Hopefully the weather will be nice tomorrow for the picnic.",
        "verb_form": "haga",
        "verb_infinitive": "hacer",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Haga\" is the present subjunctive of hacer. \"Ojalá\" always requires the subjunctive.",
    },
    {
        "id": 55,
        "spanish": "Te llamo cuando llegue al aeropuerto, ¿de acuerdo?",
        "english": "I'll call you when I arrive at the airport, OK?",
        "verb_form": "llegue",
        "verb_infinitive": "llegar",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Llegue\" is the present subjunctive of llegar. \"Cuando\" referring to a future event requires the subjunctive.",
    },
    {
        "id": 56,
        "spanish": "Es una pena que no puedas venir a la cena.",
        "english": "It is a shame that you can't come to the dinner.",
        "verb_form": "puedas",
        "verb_infinitive": "poder",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Puedas\" is the present subjunctive of the stem-changing poder, after \"es una pena que\".",
    },

    # ── Imperativo ──────────────────────────────────────────────────────────
    {
        "id": 57,
        "spanish": "Habla más despacio, por favor, que no te entiendo bien.",
        "english": "Speak more slowly, please — I can't understand you well.",
        "verb_form": "habla",
        "verb_infinitive": "hablar",
        "tense": "Imperativo",
        "explanation": "\"Habla\" is the affirmative imperative of hablar (tú form), giving a direct instruction.",
    },
    {
        "id": 58,
        "spanish": "Comed las verduras antes de pedir el postre.",
        "english": "Eat your vegetables before asking for dessert.",
        "verb_form": "comed",
        "verb_infinitive": "comer",
        "tense": "Imperativo",
        "explanation": "\"Comed\" is the affirmative imperative of comer (vosotros form).",
    },
    {
        "id": 59,
        "spanish": "Escuchad bien las instrucciones antes de empezar el ejercicio.",
        "english": "Listen carefully to the instructions before starting the exercise.",
        "verb_form": "escuchad",
        "verb_infinitive": "escuchar",
        "tense": "Imperativo",
        "explanation": "\"Escuchad\" is the affirmative imperative of escuchar (vosotros form).",
    },
    {
        "id": 60,
        "spanish": "Ven aquí un momento, que tengo algo importante que contarte.",
        "english": "Come here for a moment — I have something important to tell you.",
        "verb_form": "ven",
        "verb_infinitive": "venir",
        "tense": "Imperativo",
        "explanation": "\"Ven\" is the irregular affirmative imperative of venir (tú form).",
    },
    {
        "id": 61,
        "spanish": "Abrid el libro por la página cincuenta y tres.",
        "english": "Open your books at page fifty-three.",
        "verb_form": "abrid",
        "verb_infinitive": "abrir",
        "tense": "Imperativo",
        "explanation": "\"Abrid\" is the affirmative imperative of abrir (vosotros form).",
    },
    {
        "id": 62,
        "spanish": "Dime la verdad, no tengas miedo.",
        "english": "Tell me the truth — don't be afraid.",
        "verb_form": "dime",
        "verb_infinitive": "decir",
        "tense": "Imperativo",
        "explanation": "\"Dime\" is the irregular imperative of decir (tú form) with an attached pronoun.",
    },
    {
        "id": 63,
        "spanish": "Salid del edificio inmediatamente, hay una emergencia.",
        "english": "Leave the building immediately — there is an emergency.",
        "verb_form": "salid",
        "verb_infinitive": "salir",
        "tense": "Imperativo",
        "explanation": "\"Salid\" is the affirmative imperative of salir (vosotros form).",
    },
    {
        "id": 64,
        "spanish": "Ponlo en la mesa y cierra la puerta al salir.",
        "english": "Put it on the table and close the door on your way out.",
        "verb_form": "ponlo",
        "verb_infinitive": "poner",
        "tense": "Imperativo",
        "explanation": "\"Ponlo\" is the irregular imperative of poner (tú form) with an attached pronoun.",
    },

    # ── Irregular verbs — Presente de indicativo ────────────────────────────
    {
        "id": 65,
        "spanish": "Soy profesora de matemáticas en un instituto público.",
        "english": "I am a maths teacher at a state secondary school.",
        "verb_form": "soy",
        "verb_infinitive": "ser",
        "tense": "Presente de indicativo",
        "explanation": "\"Soy\" is the highly irregular present indicative of ser (1st person singular).",
    },
    {
        "id": 66,
        "spanish": "Voy al mercado todos los sábados por la mañana.",
        "english": "I go to the market every Saturday morning.",
        "verb_form": "voy",
        "verb_infinitive": "ir",
        "tense": "Presente de indicativo",
        "explanation": "\"Voy\" is the irregular present indicative of ir (1st person singular).",
    },
    {
        "id": 67,
        "spanish": "Siempre trae algo rico cuando viene a cenar.",
        "english": "He always brings something nice when he comes for dinner.",
        "verb_form": "trae",
        "verb_infinitive": "traer",
        "tense": "Presente de indicativo",
        "explanation": "\"Trae\" is the present indicative of traer (3rd person singular).",
    },
    {
        "id": 68,
        "spanish": "¿Oyes ese ruido extraño que viene del sótano?",
        "english": "Can you hear that strange noise coming from the basement?",
        "verb_form": "oyes",
        "verb_infinitive": "oír",
        "tense": "Presente de indicativo",
        "explanation": "\"Oyes\" is the present indicative of the irregular verb oír (2nd person singular).",
    },
    {
        "id": 69,
        "spanish": "¿Qué haces los fines de semana normalmente?",
        "english": "What do you normally do at weekends?",
        "verb_form": "haces",
        "verb_infinitive": "hacer",
        "tense": "Presente de indicativo",
        "explanation": "\"Haces\" is the present indicative of hacer (2nd person singular).",
    },
    {
        "id": 70,
        "spanish": "Siempre pongo la mesa antes de cenar en familia.",
        "english": "I always set the table before having dinner with the family.",
        "verb_form": "pongo",
        "verb_infinitive": "poner",
        "tense": "Presente de indicativo",
        "explanation": "\"Pongo\" is the irregular present indicative of poner (1st person singular, -go form).",
    },

    # ── Irregular verbs — Pretérito indefinido ──────────────────────────────
    {
        "id": 71,
        "spanish": "Fui al médico la semana pasada por el dolor de espalda.",
        "english": "I went to the doctor last week because of back pain.",
        "verb_form": "fui",
        "verb_infinitive": "ir",
        "tense": "Pretérito indefinido",
        "explanation": "\"Fui\" is the irregular preterite of ir (1st person singular). Ir and ser share the same preterite forms.",
    },
    {
        "id": 72,
        "spanish": "¿Qué hicisteis el fin de semana pasado?",
        "english": "What did you all do last weekend?",
        "verb_form": "hicisteis",
        "verb_infinitive": "hacer",
        "tense": "Pretérito indefinido",
        "explanation": "\"Hicisteis\" is the irregular preterite of hacer (2nd person plural).",
    },
    {
        "id": 73,
        "spanish": "Mis primos vinieron a visitarnos desde Sevilla.",
        "english": "My cousins came to visit us from Seville.",
        "verb_form": "vinieron",
        "verb_infinitive": "venir",
        "tense": "Pretérito indefinido",
        "explanation": "\"Vinieron\" is the irregular preterite of venir (3rd person plural).",
    },
    {
        "id": 74,
        "spanish": "El médico dijo que necesitaba descansar más.",
        "english": "The doctor said I needed to rest more.",
        "verb_form": "dijo",
        "verb_infinitive": "decir",
        "tense": "Pretérito indefinido",
        "explanation": "\"Dijo\" is the irregular preterite of decir (3rd person singular).",
    },
    {
        "id": 75,
        "spanish": "No pude terminar el informe a tiempo.",
        "english": "I couldn't finish the report on time.",
        "verb_form": "pude",
        "verb_infinitive": "poder",
        "tense": "Pretérito indefinido",
        "explanation": "\"Pude\" is the irregular preterite of poder (1st person singular).",
    },
    {
        "id": 76,
        "spanish": "Traje demasiadas cosas en la maleta del viaje.",
        "english": "I brought too many things in my suitcase.",
        "verb_form": "traje",
        "verb_infinitive": "traer",
        "tense": "Pretérito indefinido",
        "explanation": "\"Traje\" is the irregular preterite of traer (1st person singular).",
    },

    # ── Irregular verbs — Pretérito imperfecto ──────────────────────────────
    {
        "id": 77,
        "spanish": "De niño, era muy tímido en clase y casi no hablaba.",
        "english": "As a child, I was very shy in class and barely spoke.",
        "verb_form": "era",
        "verb_infinitive": "ser",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Era\" is the imperfect of ser (1st person singular), one of only three irregular imperfects in Spanish.",
    },
    {
        "id": 78,
        "spanish": "Antes podía correr diez kilómetros sin parar.",
        "english": "I used to be able to run ten kilometres without stopping.",
        "verb_form": "podía",
        "verb_infinitive": "poder",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Podía\" is the imperfect of poder (1st person singular), describing a past ability.",
    },
    {
        "id": 79,
        "spanish": "Veíamos la televisión juntos todas las noches.",
        "english": "We used to watch television together every evening.",
        "verb_form": "veíamos",
        "verb_infinitive": "ver",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Veíamos\" is the imperfect of ver (1st person plural). Ver has an irregular imperfect stem.",
    },
    {
        "id": 80,
        "spanish": "De joven quería ser médico de urgencias.",
        "english": "When I was young, I wanted to be an emergency doctor.",
        "verb_form": "quería",
        "verb_infinitive": "querer",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Quería\" is the imperfect of querer (1st person singular), describing a past aspiration.",
    },
    {
        "id": 81,
        "spanish": "Venían a cenar a nuestra casa todos los viernes.",
        "english": "They used to come for dinner at our house every Friday.",
        "verb_form": "venían",
        "verb_infinitive": "venir",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Venían\" is the imperfect of venir (3rd person plural), describing a regular past habit.",
    },
    {
        "id": 82,
        "spanish": "Siempre decía que la vida era demasiado corta.",
        "english": "He always used to say that life was too short.",
        "verb_form": "decía",
        "verb_infinitive": "decir",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Decía\" is the imperfect of decir (3rd person singular), describing a habitual past statement.",
    },

    # ── Irregular verbs — Pretérito perfecto compuesto ──────────────────────
    {
        "id": 83,
        "spanish": "¿Qué has hecho este fin de semana tan largo?",
        "english": "What have you done this long weekend?",
        "verb_form": "has hecho",
        "verb_infinitive": "hacer",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Has hecho\" uses the irregular past participle of hacer (hecho), not the regular *hacido.",
    },
    {
        "id": 84,
        "spanish": "¿Has visto las noticias esta mañana en la televisión?",
        "english": "Have you seen the news this morning on television?",
        "verb_form": "has visto",
        "verb_infinitive": "ver",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Has visto\" uses the irregular past participle of ver (visto), not the regular *vido.",
    },
    {
        "id": 85,
        "spanish": "No he podido dormir bien en toda la semana.",
        "english": "I haven't been able to sleep well all week.",
        "verb_form": "he podido",
        "verb_infinitive": "poder",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"He podido\" is the present perfect of poder (1st person singular).",
    },
    {
        "id": 86,
        "spanish": "Han vuelto de su viaje de novios esta mañana.",
        "english": "They have returned from their honeymoon this morning.",
        "verb_form": "han vuelto",
        "verb_infinitive": "volver",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Han vuelto\" uses the irregular past participle of volver (vuelto).",
    },
    {
        "id": 87,
        "spanish": "He puesto el despertador para las seis y media.",
        "english": "I have set the alarm for half past six.",
        "verb_form": "he puesto",
        "verb_infinitive": "poner",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"He puesto\" uses the irregular past participle of poner (puesto).",
    },
    {
        "id": 88,
        "spanish": "Me han dicho que tiene que operarse de rodilla.",
        "english": "I have been told that he needs a knee operation.",
        "verb_form": "han dicho",
        "verb_infinitive": "decir",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Han dicho\" uses the irregular past participle of decir (dicho).",
    },

    # ── Irregular verbs — Futuro simple ─────────────────────────────────────
    {
        "id": 89,
        "spanish": "Tendrás que madrugar para coger ese tren tan temprano.",
        "english": "You'll have to get up early to catch that train.",
        "verb_form": "tendrás",
        "verb_infinitive": "tener",
        "tense": "Futuro simple",
        "explanation": "\"Tendrás\" is the irregular future of tener (2nd person singular). The stem changes to tendr-.",
    },
    {
        "id": 90,
        "spanish": "¿Podréis venir a la boda el próximo mes de junio?",
        "english": "Will you all be able to come to the wedding next June?",
        "verb_form": "podréis",
        "verb_infinitive": "poder",
        "tense": "Futuro simple",
        "explanation": "\"Podréis\" is the irregular future of poder (2nd person plural). The stem changes to podr-.",
    },
    {
        "id": 91,
        "spanish": "No sé qué haré cuando termine la carrera.",
        "english": "I don't know what I'll do when I finish my degree.",
        "verb_form": "haré",
        "verb_infinitive": "hacer",
        "tense": "Futuro simple",
        "explanation": "\"Haré\" is the irregular future of hacer (1st person singular). The stem changes to har-.",
    },
    {
        "id": 92,
        "spanish": "Vendrán todos los familiares a la cena de Navidad.",
        "english": "All the relatives will come to the Christmas dinner.",
        "verb_form": "vendrán",
        "verb_infinitive": "venir",
        "tense": "Futuro simple",
        "explanation": "\"Vendrán\" is the irregular future of venir (3rd person plural). The stem changes to vendr-.",
    },
    {
        "id": 93,
        "spanish": "Les diremos la verdad cuando llegue el momento adecuado.",
        "english": "We will tell them the truth when the right moment comes.",
        "verb_form": "diremos",
        "verb_infinitive": "decir",
        "tense": "Futuro simple",
        "explanation": "\"Diremos\" is the irregular future of decir (1st person plural). The stem changes to dir-.",
    },
    {
        "id": 94,
        "spanish": "Sabrás la nota del examen la semana que viene.",
        "english": "You'll know your exam grade next week.",
        "verb_form": "sabrás",
        "verb_infinitive": "saber",
        "tense": "Futuro simple",
        "explanation": "\"Sabrás\" is the irregular future of saber (2nd person singular). The stem changes to sabr-.",
    },

    # ── Irregular verbs — Condicional simple ────────────────────────────────
    {
        "id": 95,
        "spanish": "Tendría más energía si durmiera mejor cada noche.",
        "english": "I would have more energy if I slept better each night.",
        "verb_form": "tendría",
        "verb_infinitive": "tener",
        "tense": "Condicional simple",
        "explanation": "\"Tendría\" is the conditional of tener (1st person singular). Uses the same irregular stem as the future: tendr-.",
    },
    {
        "id": 96,
        "spanish": "¿Podría hablar con el director un momento, por favor?",
        "english": "Could I speak with the manager for a moment, please?",
        "verb_form": "podría",
        "verb_infinitive": "poder",
        "tense": "Condicional simple",
        "explanation": "\"Podría\" is the conditional of poder (1st person singular), used for a polite request.",
    },
    {
        "id": 97,
        "spanish": "¿Qué harías si te tocara la lotería esta semana?",
        "english": "What would you do if you won the lottery this week?",
        "verb_form": "harías",
        "verb_infinitive": "hacer",
        "tense": "Condicional simple",
        "explanation": "\"Harías\" is the conditional of hacer (2nd person singular). Uses the irregular stem har-.",
    },
    {
        "id": 98,
        "spanish": "Vendría antes si no tuviera tanto trabajo pendiente.",
        "english": "I would come earlier if I didn't have so much work outstanding.",
        "verb_form": "vendría",
        "verb_infinitive": "venir",
        "tense": "Condicional simple",
        "explanation": "\"Vendría\" is the conditional of venir (1st person singular), using the irregular stem vendr-.",
    },
    {
        "id": 99,
        "spanish": "Yo no le diría eso si estuviera en tu lugar.",
        "english": "I wouldn't say that to him if I were in your position.",
        "verb_form": "diría",
        "verb_infinitive": "decir",
        "tense": "Condicional simple",
        "explanation": "\"Diría\" is the conditional of decir (1st person singular), using the irregular stem dir-.",
    },
    {
        "id": 100,
        "spanish": "¿Sabría usted cómo llegar a la estación de tren?",
        "english": "Would you happen to know how to get to the train station?",
        "verb_form": "sabría",
        "verb_infinitive": "saber",
        "tense": "Condicional simple",
        "explanation": "\"Sabría\" is the conditional of saber (usted form), using the irregular stem sabr-.",
    },

    # ── Irregular verbs — Presente de subjuntivo ────────────────────────────
    {
        "id": 101,
        "spanish": "Espero que sea una reunión breve esta tarde.",
        "english": "I hope it is a short meeting this afternoon.",
        "verb_form": "sea",
        "verb_infinitive": "ser",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Sea\" is the present subjunctive of the irregular ser, triggered by \"espero que\".",
    },
    {
        "id": 102,
        "spanish": "Quiero que vayáis al médico esta misma semana.",
        "english": "I want you all to go to the doctor this very week.",
        "verb_form": "vayáis",
        "verb_infinitive": "ir",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Vayáis\" is the present subjunctive of the irregular ir (2nd person plural), triggered by \"quiero que\".",
    },
    {
        "id": 103,
        "spanish": "Ojalá que pueda venir a la fiesta del sábado.",
        "english": "I really hope he can come to the Saturday party.",
        "verb_form": "pueda",
        "verb_infinitive": "poder",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Pueda\" is the present subjunctive of poder. \"Ojalá\" always requires the subjunctive.",
    },
    {
        "id": 104,
        "spanish": "El jefe pide que vengamos antes de las ocho.",
        "english": "The boss asks us to come in before eight o'clock.",
        "verb_form": "vengamos",
        "verb_infinitive": "venir",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Vengamos\" is the present subjunctive of venir (1st person plural), triggered by \"pide que\".",
    },
    {
        "id": 105,
        "spanish": "Es importante que les des las gracias por todo lo que han hecho.",
        "english": "It is important that you thank them for everything they have done.",
        "verb_form": "des",
        "verb_infinitive": "dar",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Des\" is the present subjunctive of the irregular dar (2nd person singular).",
    },
    {
        "id": 106,
        "spanish": "No quiero que le digas nada a nadie todavía.",
        "english": "I don't want you to say anything to anyone yet.",
        "verb_form": "digas",
        "verb_infinitive": "decir",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Digas\" is the present subjunctive of decir (2nd person singular), triggered by \"no quiero que\".",
    },

    # ── Irregular verbs — Imperativo ────────────────────────────────────────
    {
        "id": 107,
        "spanish": "Ten paciencia, que ya casi llegamos al destino.",
        "english": "Be patient — we're almost at our destination.",
        "verb_form": "ten",
        "verb_infinitive": "tener",
        "tense": "Imperativo",
        "explanation": "\"Ten\" is the irregular affirmative imperative of tener (tú form).",
    },
    {
        "id": 108,
        "spanish": "Ve al supermercado antes de que cierre a las nueve.",
        "english": "Go to the supermarket before it closes at nine.",
        "verb_form": "ve",
        "verb_infinitive": "ir",
        "tense": "Imperativo",
        "explanation": "\"Ve\" is the irregular affirmative imperative of ir (tú form).",
    },
    {
        "id": 109,
        "spanish": "Haz la cama antes de salir de casa esta mañana.",
        "english": "Make your bed before leaving the house this morning.",
        "verb_form": "haz",
        "verb_infinitive": "hacer",
        "tense": "Imperativo",
        "explanation": "\"Haz\" is the irregular affirmative imperative of hacer (tú form).",
    },
    {
        "id": 110,
        "spanish": "Pon el abrigo, que hace mucho frío fuera.",
        "english": "Put your coat on — it's very cold outside.",
        "verb_form": "pon",
        "verb_infinitive": "poner",
        "tense": "Imperativo",
        "explanation": "\"Pon\" is the irregular affirmative imperative of poner (tú form).",
    },
    {
        "id": 111,
        "spanish": "Trae el paraguas, que parece que va a llover.",
        "english": "Bring the umbrella — it looks like it's going to rain.",
        "verb_form": "trae",
        "verb_infinitive": "traer",
        "tense": "Imperativo",
        "explanation": "\"Trae\" is the affirmative imperative of traer (tú form).",
    },
    {
        "id": 112,
        "spanish": "Venid pronto, que la cena se va a enfriar.",
        "english": "Come quickly — dinner is going to get cold.",
        "verb_form": "venid",
        "verb_infinitive": "venir",
        "tense": "Imperativo",
        "explanation": "\"Venid\" is the affirmative imperative of venir (vosotros form).",
    },
]
