TENSES = [
    "Presente de indicativo",
    "Pretérito indefinido",
    "Pretérito imperfecto",
    "Pretérito perfecto compuesto",
    "Futuro simple",
    "Condicional simple",
    "Presente de subjuntivo",
    "Imperativo",
]

SENTENCES = [
    # ── Presente de indicativo ──────────────────────────────────────────────
    {
        "id": 1,
        "spanish": "Todos los días como una manzana en el desayuno.",
        "english": "Every day I eat an apple for breakfast.",
        "verb_form": "como",
        "verb_infinitive": "comer",
        "tense": "Presente de indicativo",
        "explanation": "\"Como\" is the present indicative of comer (1st person singular), describing a habitual action.",
    },
    {
        "id": 2,
        "spanish": "Mi hermana trabaja en un hospital del centro.",
        "english": "My sister works at a hospital in the city centre.",
        "verb_form": "trabaja",
        "verb_infinitive": "trabajar",
        "tense": "Presente de indicativo",
        "explanation": "\"Trabaja\" is the present indicative of trabajar (3rd person singular).",
    },
    {
        "id": 3,
        "spanish": "Nosotros vivimos cerca de la playa.",
        "english": "We live near the beach.",
        "verb_form": "vivimos",
        "verb_infinitive": "vivir",
        "tense": "Presente de indicativo",
        "explanation": "\"Vivimos\" is the present indicative of vivir (1st person plural).",
    },
    {
        "id": 4,
        "spanish": "¿Hablas español con tu familia en casa?",
        "english": "Do you speak Spanish with your family at home?",
        "verb_form": "hablas",
        "verb_infinitive": "hablar",
        "tense": "Presente de indicativo",
        "explanation": "\"Hablas\" is the present indicative of hablar (2nd person singular).",
    },
    {
        "id": 5,
        "spanish": "Los niños juegan en el parque por las tardes.",
        "english": "The children play in the park in the afternoons.",
        "verb_form": "juegan",
        "verb_infinitive": "jugar",
        "tense": "Presente de indicativo",
        "explanation": "\"Juegan\" is the present indicative of the stem-changing verb jugar (3rd person plural).",
    },
    {
        "id": 6,
        "spanish": "El tren sale a las nueve de la mañana.",
        "english": "The train leaves at nine in the morning.",
        "verb_form": "sale",
        "verb_infinitive": "salir",
        "tense": "Presente de indicativo",
        "explanation": "\"Sale\" is the present indicative of salir (3rd person singular).",
    },
    {
        "id": 7,
        "spanish": "Vosotros estudiáis mucho para los exámenes.",
        "english": "You all study a lot for the exams.",
        "verb_form": "estudiáis",
        "verb_infinitive": "estudiar",
        "tense": "Presente de indicativo",
        "explanation": "\"Estudiáis\" is the present indicative of estudiar (2nd person plural, vosotros).",
    },
    {
        "id": 8,
        "spanish": "Siempre llueve mucho en otoño en el norte.",
        "english": "It always rains a lot in autumn in the north.",
        "verb_form": "llueve",
        "verb_infinitive": "llover",
        "tense": "Presente de indicativo",
        "explanation": "\"Llueve\" is the present indicative of the impersonal verb llover.",
    },

    # ── Pretérito indefinido ────────────────────────────────────────────────
    {
        "id": 9,
        "spanish": "Ayer comí una paella deliciosa en el restaurante.",
        "english": "Yesterday I ate a delicious paella at the restaurant.",
        "verb_form": "comí",
        "verb_infinitive": "comer",
        "tense": "Pretérito indefinido",
        "explanation": "\"Comí\" is the preterite of comer (1st person singular). The word ayer confirms a completed past action.",
    },
    {
        "id": 10,
        "spanish": "María llegó a casa muy tarde anoche.",
        "english": "María arrived home very late last night.",
        "verb_form": "llegó",
        "verb_infinitive": "llegar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Llegó\" is the preterite of llegar (3rd person singular), a completed action in the past.",
    },
    {
        "id": 11,
        "spanish": "Los estudiantes aprobaron todos los exámenes finales.",
        "english": "The students passed all the final exams.",
        "verb_form": "aprobaron",
        "verb_infinitive": "aprobar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Aprobaron\" is the preterite of aprobar (3rd person plural).",
    },
    {
        "id": 12,
        "spanish": "El partido terminó con un resultado de tres a uno.",
        "english": "The match ended with a score of three to one.",
        "verb_form": "terminó",
        "verb_infinitive": "terminar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Terminó\" is the preterite of terminar (3rd person singular).",
    },
    {
        "id": 13,
        "spanish": "¿Cuándo empezaste a estudiar español?",
        "english": "When did you start studying Spanish?",
        "verb_form": "empezaste",
        "verb_infinitive": "empezar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Empezaste\" is the preterite of empezar (2nd person singular).",
    },
    {
        "id": 14,
        "spanish": "Bebieron demasiado vino en la cena de Navidad.",
        "english": "They drank too much wine at the Christmas dinner.",
        "verb_form": "bebieron",
        "verb_infinitive": "beber",
        "tense": "Pretérito indefinido",
        "explanation": "\"Bebieron\" is the preterite of beber (3rd person plural).",
    },
    {
        "id": 15,
        "spanish": "Anteayer hablé con mi madre por teléfono durante una hora.",
        "english": "The day before yesterday I spoke with my mother on the phone for an hour.",
        "verb_form": "hablé",
        "verb_infinitive": "hablar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Hablé\" is the preterite of hablar (1st person singular).",
    },
    {
        "id": 16,
        "spanish": "El año pasado viajamos a Madrid durante las vacaciones.",
        "english": "Last year we travelled to Madrid during the holidays.",
        "verb_form": "viajamos",
        "verb_infinitive": "viajar",
        "tense": "Pretérito indefinido",
        "explanation": "\"Viajamos\" here is the preterite of viajar — the phrase \"el año pasado\" signals a completed past event.",
    },

    # ── Pretérito imperfecto ────────────────────────────────────────────────
    {
        "id": 17,
        "spanish": "Cuando era niño, vivía en un pueblo pequeño del norte.",
        "english": "When I was a child, I lived in a small town in the north.",
        "verb_form": "vivía",
        "verb_infinitive": "vivir",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Vivía\" is the imperfect of vivir, describing an ongoing past situation.",
    },
    {
        "id": 18,
        "spanish": "De pequeña, mi abuela cocinaba todos los domingos para la familia.",
        "english": "When she was little, my grandmother cooked for the family every Sunday.",
        "verb_form": "cocinaba",
        "verb_infinitive": "cocinar",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Cocinaba\" is the imperfect of cocinar, describing a repeated past habit.",
    },
    {
        "id": 19,
        "spanish": "Antes, los niños jugaban más en la calle y menos con el móvil.",
        "english": "Before, children used to play more in the street and less with their phones.",
        "verb_form": "jugaban",
        "verb_infinitive": "jugar",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Jugaban\" is the imperfect of jugar, describing a habitual past activity.",
    },
    {
        "id": 20,
        "spanish": "Cuando llegué a casa, mis hijos dormían tranquilamente.",
        "english": "When I arrived home, my children were sleeping peacefully.",
        "verb_form": "dormían",
        "verb_infinitive": "dormir",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Dormían\" is the imperfect of dormir — an ongoing action interrupted by another (llegué).",
    },
    {
        "id": 21,
        "spanish": "Todos los veranos íbamos a la playa con los abuelos.",
        "english": "Every summer we used to go to the beach with our grandparents.",
        "verb_form": "íbamos",
        "verb_infinitive": "ir",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Íbamos\" is the imperfect of the irregular verb ir, expressing a past routine.",
    },
    {
        "id": 22,
        "spanish": "Cuando era joven, soñaba con ser astronauta.",
        "english": "When I was young, I used to dream of being an astronaut.",
        "verb_form": "soñaba",
        "verb_infinitive": "soñar",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Soñaba\" is the imperfect of soñar, describing a recurring past wish.",
    },
    {
        "id": 23,
        "spanish": "En aquella época, la gente no tenía teléfonos móviles.",
        "english": "In those days, people didn't have mobile phones.",
        "verb_form": "tenía",
        "verb_infinitive": "tener",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Tenía\" is the imperfect of tener, describing a past state.",
    },
    {
        "id": 24,
        "spanish": "Mientras estudiaba, escuchaba música clásica.",
        "english": "While I was studying, I was listening to classical music.",
        "verb_form": "estudiaba",
        "verb_infinitive": "estudiar",
        "tense": "Pretérito imperfecto",
        "explanation": "\"Estudiaba\" is the imperfect of estudiar, describing two simultaneous ongoing past actions.",
    },

    # ── Pretérito perfecto compuesto ────────────────────────────────────────
    {
        "id": 25,
        "spanish": "Esta mañana he desayunado con mi familia antes del trabajo.",
        "english": "This morning I had breakfast with my family before work.",
        "verb_form": "he desayunado",
        "verb_infinitive": "desayunar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"He desayunado\" is the present perfect of desayunar. \"Esta mañana\" signals a recently completed action.",
    },
    {
        "id": 26,
        "spanish": "¿Alguna vez has visitado la Sagrada Familia en Barcelona?",
        "english": "Have you ever visited the Sagrada Família in Barcelona?",
        "verb_form": "has visitado",
        "verb_infinitive": "visitar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Has visitado\" is the present perfect of visitar, used for life experiences with \"alguna vez\".",
    },
    {
        "id": 27,
        "spanish": "Esta semana hemos trabajado muchísimo para terminar el proyecto.",
        "english": "This week we have worked a great deal to finish the project.",
        "verb_form": "hemos trabajado",
        "verb_infinitive": "trabajar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Hemos trabajado\" is the present perfect of trabajar. \"Esta semana\" links the action to the present period.",
    },
    {
        "id": 28,
        "spanish": "Mis padres han comprado una casa nueva en las afueras.",
        "english": "My parents have bought a new house on the outskirts.",
        "verb_form": "han comprado",
        "verb_infinitive": "comprar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Han comprado\" is the present perfect of comprar (3rd person plural).",
    },
    {
        "id": 29,
        "spanish": "Hoy el ministro ha anunciado cambios importantes en la ley.",
        "english": "Today the minister has announced important changes to the law.",
        "verb_form": "ha anunciado",
        "verb_infinitive": "anunciar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Ha anunciado\" is the present perfect of anunciar. \"Hoy\" places it in the current time frame.",
    },
    {
        "id": 30,
        "spanish": "Nunca he probado el gazpacho andaluz.",
        "english": "I have never tried Andalusian gazpacho.",
        "verb_form": "he probado",
        "verb_infinitive": "probar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"He probado\" with \"nunca\" is a classic present perfect structure for life experiences.",
    },
    {
        "id": 31,
        "spanish": "¿Ya habéis terminado los deberes para mañana?",
        "english": "Have you all already finished the homework for tomorrow?",
        "verb_form": "habéis terminado",
        "verb_infinitive": "terminar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Habéis terminado\" is the present perfect of terminar (2nd person plural, vosotros).",
    },
    {
        "id": 32,
        "spanish": "Este año España ha ganado varios premios internacionales.",
        "english": "This year Spain has won several international awards.",
        "verb_form": "ha ganado",
        "verb_infinitive": "ganar",
        "tense": "Pretérito perfecto compuesto",
        "explanation": "\"Ha ganado\" is the present perfect of ganar. \"Este año\" connects to the ongoing present year.",
    },

    # ── Futuro simple ───────────────────────────────────────────────────────
    {
        "id": 33,
        "spanish": "El próximo verano viajaré por toda Andalucía.",
        "english": "Next summer I will travel all around Andalusia.",
        "verb_form": "viajaré",
        "verb_infinitive": "viajar",
        "tense": "Futuro simple",
        "explanation": "\"Viajaré\" is the simple future of viajar (1st person singular).",
    },
    {
        "id": 34,
        "spanish": "Mañana hará mucho calor en el sur de España.",
        "english": "Tomorrow it will be very hot in southern Spain.",
        "verb_form": "hará",
        "verb_infinitive": "hacer",
        "tense": "Futuro simple",
        "explanation": "\"Hará\" is the simple future of the irregular verb hacer (3rd person singular).",
    },
    {
        "id": 35,
        "spanish": "Cuando termines los estudios, encontrarás un buen trabajo.",
        "english": "When you finish your studies, you will find a good job.",
        "verb_form": "encontrarás",
        "verb_infinitive": "encontrar",
        "tense": "Futuro simple",
        "explanation": "\"Encontrarás\" is the simple future of encontrar (2nd person singular).",
    },
    {
        "id": 36,
        "spanish": "El concierto empezará a las nueve y terminará a medianoche.",
        "english": "The concert will start at nine and end at midnight.",
        "verb_form": "empezará",
        "verb_infinitive": "empezar",
        "tense": "Futuro simple",
        "explanation": "\"Empezará\" is the simple future of empezar (3rd person singular).",
    },
    {
        "id": 37,
        "spanish": "El año que viene construirán un nuevo hospital en esta ciudad.",
        "english": "Next year they will build a new hospital in this city.",
        "verb_form": "construirán",
        "verb_infinitive": "construir",
        "tense": "Futuro simple",
        "explanation": "\"Construirán\" is the simple future of construir (3rd person plural).",
    },
    {
        "id": 38,
        "spanish": "Prometo que vendré a tu boda sin falta.",
        "english": "I promise I will come to your wedding without fail.",
        "verb_form": "vendré",
        "verb_infinitive": "venir",
        "tense": "Futuro simple",
        "explanation": "\"Vendré\" is the simple future of the irregular verb venir (1st person singular).",
    },
    {
        "id": 39,
        "spanish": "¿Cuánto tiempo tardaréis en llegar a Madrid desde aquí?",
        "english": "How long will it take you all to get to Madrid from here?",
        "verb_form": "tardaréis",
        "verb_infinitive": "tardar",
        "tense": "Futuro simple",
        "explanation": "\"Tardaréis\" is the simple future of tardar (2nd person plural, vosotros).",
    },
    {
        "id": 40,
        "spanish": "No sé dónde estará mi pasaporte; lo buscaré después.",
        "english": "I don't know where my passport will be; I'll look for it later.",
        "verb_form": "estará",
        "verb_infinitive": "estar",
        "tense": "Futuro simple",
        "explanation": "\"Estará\" is the simple future of estar, used here to express probability or conjecture.",
    },

    # ── Condicional simple ──────────────────────────────────────────────────
    {
        "id": 41,
        "spanish": "Si tuviera más dinero, compraría una casa en la playa.",
        "english": "If I had more money, I would buy a house on the beach.",
        "verb_form": "compraría",
        "verb_infinitive": "comprar",
        "tense": "Condicional simple",
        "explanation": "\"Compraría\" is the conditional of comprar, used in a hypothetical if-clause.",
    },
    {
        "id": 42,
        "spanish": "¿Podrías ayudarme con este ejercicio, por favor?",
        "english": "Could you help me with this exercise, please?",
        "verb_form": "podrías",
        "verb_infinitive": "poder",
        "tense": "Condicional simple",
        "explanation": "\"Podrías\" is the conditional of the irregular poder, used for polite requests.",
    },
    {
        "id": 43,
        "spanish": "Me dijo que llamaría cuando llegara a casa.",
        "english": "He told me he would call when he got home.",
        "verb_form": "llamaría",
        "verb_infinitive": "llamar",
        "tense": "Condicional simple",
        "explanation": "\"Llamaría\" is the conditional of llamar, used as a future-in-the-past after a reporting verb.",
    },
    {
        "id": 44,
        "spanish": "En tu lugar, hablaría directamente con el director.",
        "english": "In your place, I would speak directly to the director.",
        "verb_form": "hablaría",
        "verb_infinitive": "hablar",
        "tense": "Condicional simple",
        "explanation": "\"Hablaría\" is the conditional of hablar, giving advice about a hypothetical situation.",
    },
    {
        "id": 45,
        "spanish": "¿Sabrías cómo llegar a la catedral desde aquí?",
        "english": "Would you happen to know how to get to the cathedral from here?",
        "verb_form": "sabrías",
        "verb_infinitive": "saber",
        "tense": "Condicional simple",
        "explanation": "\"Sabrías\" is the conditional of the irregular saber, softening a question politely.",
    },
    {
        "id": 46,
        "spanish": "Con más tiempo libre, estudiaríamos mucho mejor.",
        "english": "With more free time, we would study much better.",
        "verb_form": "estudiaríamos",
        "verb_infinitive": "estudiar",
        "tense": "Condicional simple",
        "explanation": "\"Estudiaríamos\" is the conditional of estudiar (1st person plural).",
    },
    {
        "id": 47,
        "spanish": "¿Querrías venir a la fiesta del sábado con nosotros?",
        "english": "Would you like to come to the Saturday party with us?",
        "verb_form": "querrías",
        "verb_infinitive": "querer",
        "tense": "Condicional simple",
        "explanation": "\"Querrías\" is the conditional of the irregular querer, used for a polite invitation.",
    },
    {
        "id": 48,
        "spanish": "Pensaban que el proyecto costaría mucho menos.",
        "english": "They thought the project would cost much less.",
        "verb_form": "costaría",
        "verb_infinitive": "costar",
        "tense": "Condicional simple",
        "explanation": "\"Costaría\" is the conditional of costar, expressing a past expectation about the future.",
    },

    # ── Presente de subjuntivo ──────────────────────────────────────────────
    {
        "id": 49,
        "spanish": "Espero que llegues a tiempo para la reunión.",
        "english": "I hope you arrive on time for the meeting.",
        "verb_form": "llegues",
        "verb_infinitive": "llegar",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Llegues\" is the present subjunctive of llegar, triggered by \"espero que\".",
    },
    {
        "id": 50,
        "spanish": "El médico recomienda que bebas mucha agua cada día.",
        "english": "The doctor recommends that you drink plenty of water each day.",
        "verb_form": "bebas",
        "verb_infinitive": "beber",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Bebas\" is the present subjunctive of beber, triggered by \"recomienda que\".",
    },
    {
        "id": 51,
        "spanish": "Es importante que hagamos ejercicio con regularidad.",
        "english": "It is important that we exercise regularly.",
        "verb_form": "hagamos",
        "verb_infinitive": "hacer",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Hagamos\" is the present subjunctive of the irregular hacer, following the impersonal \"es importante que\".",
    },
    {
        "id": 52,
        "spanish": "No creo que tenga razón en este asunto.",
        "english": "I don't think he is right about this matter.",
        "verb_form": "tenga",
        "verb_infinitive": "tener",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Tenga\" is the present subjunctive of tener, triggered by the negative \"no creo que\".",
    },
    {
        "id": 53,
        "spanish": "Busco a alguien que sepa hablar chino con fluidez.",
        "english": "I am looking for someone who can speak Chinese fluently.",
        "verb_form": "sepa",
        "verb_infinitive": "saber",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Sepa\" is the present subjunctive of saber, used in a relative clause with an unknown/indefinite antecedent.",
    },
    {
        "id": 54,
        "spanish": "Ojalá que mañana haga buen tiempo para el picnic.",
        "english": "Hopefully the weather will be nice tomorrow for the picnic.",
        "verb_form": "haga",
        "verb_infinitive": "hacer",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Haga\" is the present subjunctive of hacer. \"Ojalá\" always requires the subjunctive.",
    },
    {
        "id": 55,
        "spanish": "Te llamo cuando llegue al aeropuerto, ¿de acuerdo?",
        "english": "I'll call you when I arrive at the airport, OK?",
        "verb_form": "llegue",
        "verb_infinitive": "llegar",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Llegue\" is the present subjunctive of llegar. \"Cuando\" referring to a future event requires the subjunctive.",
    },
    {
        "id": 56,
        "spanish": "Es una pena que no puedas venir a la cena.",
        "english": "It is a shame that you can't come to the dinner.",
        "verb_form": "puedas",
        "verb_infinitive": "poder",
        "tense": "Presente de subjuntivo",
        "explanation": "\"Puedas\" is the present subjunctive of the stem-changing poder, after \"es una pena que\".",
    },

    # ── Imperativo ──────────────────────────────────────────────────────────
    {
        "id": 57,
        "spanish": "Habla más despacio, por favor, que no te entiendo bien.",
        "english": "Speak more slowly, please — I can't understand you well.",
        "verb_form": "habla",
        "verb_infinitive": "hablar",
        "tense": "Imperativo",
        "explanation": "\"Habla\" is the affirmative imperative of hablar (tú form), giving a direct instruction.",
    },
    {
        "id": 58,
        "spanish": "Comed las verduras antes de pedir el postre.",
        "english": "Eat your vegetables before asking for dessert.",
        "verb_form": "comed",
        "verb_infinitive": "comer",
        "tense": "Imperativo",
        "explanation": "\"Comed\" is the affirmative imperative of comer (vosotros form).",
    },
    {
        "id": 59,
        "spanish": "Escuchad bien las instrucciones antes de empezar el ejercicio.",
        "english": "Listen carefully to the instructions before starting the exercise.",
        "verb_form": "escuchad",
        "verb_infinitive": "escuchar",
        "tense": "Imperativo",
        "explanation": "\"Escuchad\" is the affirmative imperative of escuchar (vosotros form).",
    },
    {
        "id": 60,
        "spanish": "Ven aquí un momento, que tengo algo importante que contarte.",
        "english": "Come here for a moment — I have something important to tell you.",
        "verb_form": "ven",
        "verb_infinitive": "venir",
        "tense": "Imperativo",
        "explanation": "\"Ven\" is the irregular affirmative imperative of venir (tú form).",
    },
    {
        "id": 61,
        "spanish": "Abrid el libro por la página cincuenta y tres.",
        "english": "Open your books at page fifty-three.",
        "verb_form": "abrid",
        "verb_infinitive": "abrir",
        "tense": "Imperativo",
        "explanation": "\"Abrid\" is the affirmative imperative of abrir (vosotros form).",
    },
    {
        "id": 62,
        "spanish": "Dime la verdad, no tengas miedo.",
        "english": "Tell me the truth — don't be afraid.",
        "verb_form": "dime",
        "verb_infinitive": "decir",
        "tense": "Imperativo",
        "explanation": "\"Dime\" is the irregular imperative of decir (tú form) with an attached pronoun.",
    },
    {
        "id": 63,
        "spanish": "Salid del edificio inmediatamente, hay una emergencia.",
        "english": "Leave the building immediately — there is an emergency.",
        "verb_form": "salid",
        "verb_infinitive": "salir",
        "tense": "Imperativo",
        "explanation": "\"Salid\" is the affirmative imperative of salir (vosotros form).",
    },
    {
        "id": 64,
        "spanish": "Ponlo en la mesa y cierra la puerta al salir.",
        "english": "Put it on the table and close the door on your way out.",
        "verb_form": "ponlo",
        "verb_infinitive": "poner",
        "tense": "Imperativo",
        "explanation": "\"Ponlo\" is the irregular imperative of poner (tú form) with an attached pronoun.",
    },
]
